### ISSUE TITLE
accelerate launch train.py not showing progress bar

### ISSUE THREAD

**Issue by weiddeng** [lucidrains/denoising-diffusion-pytorch#198]
I was following Multi-GPU Training instructions here https://github.com/lucidrains/denoising-diffusion-pytorch#multi-gpu-training
(I have 2 GPUs) but upon running `accelerate launch train.py` I didn't see the tqdm bar. Did I miss something? Thank you very much!

**Comment by DavidXie03** [comment]
check https://huggingface.co/docs/accelerate/index for details

**Comment by weiddeng** [comment]
Thank you so much DavidXie03!

I was bitten by https://github.com/huggingface/accelerate/issues/314
`Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1804997 milliseconds before timing out.`
The issue probably has nothing to do with the diffusion repo.

I did some research and the timeout issue still seems unresolved for many other users, and even for those who managed to get it work it seems awkward to me as they changed timeout from 30min to 1.5 hours. Interestingly I tried the same thing on cloud GPU (whereas the error above occurred on my workstation) and it worked perfectly fine and got results under 3 mins!

I probably need to halt multi-GPU training for a while. Hopefully there will be a reasonable API soon.

**Comment by DavidXie03** [comment]
> Thank you so much DavidXie03!
> 
> I was bitten by [huggingface/accelerate#314](https://github.com/huggingface/accelerate/issues/314) `Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1804997 milliseconds before timing out.` The issue probably has nothing to do with the diffusion repo.
> 
> I did some research and the timeout issue still seems unresolved for many other users, and even for those who managed to get it work it seems awkward to me as they changed timeout from 30min to 1.5 hours. Interestingly I tried the same thing on cloud GPU (whereas the error above occurred on my workstation) and it worked perfectly fine and got results under 3 mins!
> 
> I probably need to halt multi-GPU training for a while. Hopefully there will be a reasonable API soon.

Glad that I could help you. This issue didn't happen to me because I trained the model on a remote server.

**Comment by weiddeng** [comment]
https://github.com/huggingface/accelerate/issues/314#issuecomment-1499999478 eventually fixed the issue.
