### ISSUE TITLE
GPU error: `Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.`

### ISSUE THREAD

**Issue by akshay-chenna** [lucidrains/denoising-diffusion-pytorch#229]
Hello,

I have been trying to run the 1D sequence example on a GPU (T4/V100/A100). 

I am encountering the following error on `trainer.train()`:
```
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

This is my code:
```
import torch
from denoising_diffusion_pytorch import Unet1D, GaussianDiffusion1D, Trainer1D

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = Unet1D(
    dim=64,
    dim_mults=(1, 2, 4, 8),
    channels=32
).to(device)

diffusion = GaussianDiffusion1D(
    model,
    seq_length=128,
    timesteps=1000,
    objective='pred_v'
).to(device)

training_seq = torch.rand(64, 32, 128).to(device)  # Move tensor to GPU

trainer = Trainer1D(
    diffusion,
    dataset=training_seq,
    train_batch_size=32,
    train_lr=8e-5,
    train_num_steps=700000,         # total training steps
    gradient_accumulate_every=2,    # gradient accumulation steps
    ema_decay=0.995,                # exponential moving average decay
)
trainer.train()
```

I  used the `pip install denoising_diffusion_pytorch` command for installation.
Trying to export the `CUDA_LAUNCH_BLOCKING=1` does not work.
What is the best way to solve this? Any resolution is deeply appreciated.

The entire error is as follows:

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <cell line: 32>:32                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/denoising_diffusion_pytorch/denoising_diffusion_pytorch_ │
│ 1d.py:825 in train                                                                               │
│                                                                                                  │
│   822 │   │   │   │   total_loss = 0.                                                            │
│   823 │   │   │   │                                                                              │
│   824 │   │   │   │   for _ in range(self.gradient_accumulate_every):                            │
│ ❱ 825 │   │   │   │   │   data = next(self.dl).to(device)                                        │
│   826 │   │   │   │   │                                                                          │
│   827 │   │   │   │   │   with self.accelerator.autocast():                                      │
│   828 │   │   │   │   │   │   loss = self.model(data)                                            │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/denoising_diffusion_pytorch/denoising_diffusion_pytorch_ │
│ 1d.py:43 in cycle                                                                                │
│                                                                                                  │
│    40                                                                                            │
│    41 def cycle(dl):                                                                             │
│    42 │   while True:                                                                            │
│ ❱  43 │   │   for data in dl:                                                                    │
│    44 │   │   │   yield data                                                                     │
│    45                                                                                            │
│    46 def has_int_squareroot(num):                                                               │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/accelerate/data_loader.py:377 in __iter__                │
│                                                                                                  │
│   374 │   │   dataloader_iter = super().__iter__()                                               │
│   375 │   │   # We iterate one batch ahead to check when we are at the end                       │
│   376 │   │   try:                                                                               │
│ ❱ 377 │   │   │   current_batch = next(dataloader_iter)                                          │
│   378 │   │   except StopIteration:                                                              │
│   379 │   │   │   yield                                                                          │
│   380                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:633 in __next__           │
│                                                                                                  │
│    630 │   │   │   if self._sampler_iter is None:                                                │
│    631 │   │   │   │   # TODO(https://github.com/pytorch/pytorch/issues/76750)                   │
│    632 │   │   │   │   self._reset()  # type: ignore[call-arg]                                   │
│ ❱  633 │   │   │   data = self._next_data()                                                      │
│    634 │   │   │   self._num_yielded += 1                                                        │
│    635 │   │   │   if self._dataset_kind == _DatasetKind.Iterable and \                          │
│    636 │   │   │   │   │   self._IterableDataset_len_called is not None and \                    │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:1345 in _next_data        │
│                                                                                                  │
│   1342 │   │   │   │   self._task_info[idx] += (data,)                                           │
│   1343 │   │   │   else:                                                                         │
│   1344 │   │   │   │   del self._task_info[idx]                                                  │
│ ❱ 1345 │   │   │   │   return self._process_data(data)                                           │
│   1346 │                                                                                         │
│   1347 │   def _try_put_index(self):                                                             │
│   1348 │   │   assert self._tasks_outstanding < self._prefetch_factor * self._num_workers        │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:1371 in _process_data     │
│                                                                                                  │
│   1368 │   │   self._rcvd_idx += 1                                                               │
│   1369 │   │   self._try_put_index()                                                             │
│   1370 │   │   if isinstance(data, ExceptionWrapper):                                            │
│ ❱ 1371 │   │   │   data.reraise()                                                                │
│   1372 │   │   return data                                                                       │
│   1373 │                                                                                         │
│   1374 │   def _mark_worker_as_unavailable(self, worker_id, shutdown=False):                     │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/torch/_utils.py:644 in reraise                           │
│                                                                                                  │
│   641 │   │   │   # If the exception takes multiple arguments, don't try to                      │
│   642 │   │   │   # instantiate since we don't know how to                                       │
│   643 │   │   │   raise RuntimeError(msg) from None                                              │
│ ❱ 644 │   │   raise exception                                                                    │
│   645                                                                                            │
│   646                                                                                            │
│   647 def _get_available_device_type():                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be 
incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by Adversarian** [comment]
Hi. I was able to reproduce your error on a T4 on Colab. The issue seems to be solved if you change
```python
training_seq = torch.rand(64, 32, 128).to(device)
```
to
```python
training_seq = torch.rand(64, 32, 128)
```
Note that putting `training_seq` on GPU is redundant at best since we're doing `data = next(self.dl).to(device)` at the start of each training step. However, I am not entirely certain as to why moving the training sequence to GPU from the start errors out.

**Comment by akshay-chenna** [comment]
Hello,

Thanks for the rapid solution.

I've tried implementing your solution (`training_seq = torch.rand(64, 32, 128)`) and noticed that the training time is a few thousand hours. This seems abnormal for the above code.

Im attaching a screenshot from `nvidia-smi -l 1` which shows 0%GPU  utilisation on GPU 1.
![SS](https://github.com/lucidrains/denoising-diffusion-pytorch/assets/83621245/72888d31-c09b-4566-a1b5-c449dd4baa2e)


 Also note that using 
```
loss = diffusion(training_seq)
loss.backward()
```
instead of the `Trainer1D()` runs in a few seconds. What am I missing?

Thanks,

**Comment by Adversarian** [comment]
I'm not at all well-versed in the 1D version of this repo so take this all with a grain of salt.
The code is taking long to run possibly because you've set 700k training steps on your trainer, granted it's still unusual for it to be in the thousands of hours. Your GPU usage is low because the training data that you're using is very small and your batch size is only 16.

Lastly, 
```python
loss = diffusion(training_seq)
loss.backward()
```
is a single backward step which is naturally fast. Unless you meant that you're running this for 700k steps and it runs in a few seconds which I doubt is the case.

You can make a bigger dataset and increase your batch size to see if it increases your GPU usage to make sure you're using your hardware properly.

For instance, I just ran this experiment on a T4 on Colab:

```python
import torch
from denoising_diffusion_pytorch import Unet1D, GaussianDiffusion1D, Trainer1D

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = Unet1D(
    dim=64,
    dim_mults=(1, 2, 4, 8),
    channels=32
).to(device)

diffusion = GaussianDiffusion1D(
    model,
    seq_length=128,
    timesteps=1000,
    objective='pred_v'
).to(device)

training_seq = torch.rand(1024, 32, 128)

trainer = Trainer1D(
    diffusion,
    dataset=training_seq,
    train_batch_size=512,
    train_lr=8e-5,
    train_num_steps=700000,         # total training steps
    gradient_accumulate_every=2,    # gradient accumulation steps
    ema_decay=0.995,                # exponential moving average decay
)
trainer.train()
```

This is expected to take ~260 hours and it's using 10.4 GBs of VRAM. Note the increased `train_batch_size`.

Again, these are all my guesses. I'll leave it to someone else to pick up the slack here if I'm wrong about any of the above.

**Comment by lucidrains** [comment]
@akshay-chenna ah, the example doesn't look right

the dataset should accept a `Dataset` instance that wraps all the 1 dimensional data

**Comment by lucidrains** [comment]
@akshay-chenna want to try https://github.com/lucidrains/denoising-diffusion-pytorch/commit/0a18325ccb3f048674f5464de550374b04ce59d5 ?

**Comment by akshay-chenna** [comment]
@Adversarian 
Thanks a lot for looking into my code and explaining the details.  
Yes, the small batch size is consuming lower resources and increasing it is making good use of the GPU.
I understand that `.backward()` is just one iteration.

@lucidrains thanks for updating the code, ive tested it and it works!

Closing this thread as resolved.

**Comment by lucidrains** [comment]
@akshay-chenna nice! happy training :)
